### PR TITLE
responsify-ish all (hopefully most of) the things

### PR DESCRIPTION
**Pull request by trotod**
* sort of implement a compact nav bar when shrunk
* make footer kind of responsive-ish
* responsify-ish the homepage
* sort of responsify document pages
* responsify sort of the members page
* responsify blog and posts ish

### Not yet done (but doesn't really matter)
* About page content (just go to the footer?)
* aria roles/states for nav bar thing (but that's not really important)

### CODE REVIEW

**Comment by trotod** [comment]
a terrible fix to #51, btw

**Comment by m3rcuriel** [comment]
On a scale of 1 - 10 how much should I bother to pull this

**Comment by trotod** [comment]
Eh, about a 6.

## Pros

+ It does add basic mobile support
+ People can read blog on the phone?
+ navbar is fixed (although there are better ways to fix it)

## Cons/Issues

+ It hides the document nav when on mobile (so maybe that needs to be fixed)
+ Contact page is not done (I just realized now)
+ SCSS is even messier

**Comment by m3rcuriel** [comment]
In that case, try to get those cons removed

**Comment by trotod** [comment]
Fixed some more things, besides the messy code. (Will probably rewrite/document in the future.)

(Also, what's your opinion on switching css preprocessors? [Stylus](https://github.com/learnboost/stylus) seems cooler IMO.)

**Comment by trotod** [comment]
#91

**Pull request closed without merging**
