### PR TITLE
Reset Develop

### PR DESCRIPTION
**Pull request by akalari**

### CODE REVIEW

**Comment by m3rcuriel** [comment]
This commit will… _what the wingnut did you just bosching say about me, you little rookie? I’ll have you know I graduated top of my class in electrical trainings, and I’ve been involved in numerous secret raids on 254 and 1114, and I have over 300 confirmed lines of code. I am trained in PWM crimping and I’m the top solderer in the entire Easton production chain. You are nothing to me but just another skiddie. I will wipe you under the drivetrain with PID the likes of which has never been seen before on this team, mark my abstract classes. You think you can get away with saying that scrap to me over the Internet? Think again, noobie. As we speak I am contacting my secret network of spies across 971 and 1678 and your commit is being diffed right now so you better prepare for the storm, mechie. The storm that deprecates the pathetic little thing you call your repo. Your project’s dead, kid. I can be anywhere, anytime, and I can rebase your commits in over seven hundred ways, and that’s just with the GUI. Not only am I extensively trained in C style C++, but I have access to the entire arsenal of the boost:: and OpenCV and I will use it to its full extent to wipe your miserable branch off the face of co-opertition, you little seg fault. If only you could have known what unholy retribution your little “clever” commit was about to bring down upon you, maybe you would have typed in the right tense. But you couldn’t, you didn’t, and now you’re paying the price, you infantile pleb. I will line-note fury all over you and you will drown in it. You’re mech now, kiddo._

**Comment by akalari** [comment]
Chill please.

**Comment by m3rcuriel** [comment]
Wait... do you not get it?

**Comment by akalari** [comment]
I get it. I responded with another dose of the same sarcasm, but was not
nearly as good!

**Comment by m3rcuriel** [comment]
Okay I couldn't tell. Seriously though, this flow is really annoying to deal with.

**Pull request merged**
