### PR TITLE
FIRST

### PR DESCRIPTION
**Pull request by akalari**

### CODE REVIEW

**Comment by m3rcuriel** [comment]
1) Follow commit guidelines as can be found on confluence
2) if you're just gonna merge your own PRs, just push to master ><

**Comment by akalari** [comment]
I do it for testing on dev.mvrt.com. I know there is gulp serve but it is
nice to see here as well.

**Comment by m3rcuriel** [comment]
That would be great, if you didn't just merge into master

**Comment by akalari** [comment]
I merged into master so that when you updated mvrt.com, you wouldn't have to merge.

**Comment by m3rcuriel** [comment]
That's not what I mean. If you say you pull your own PRs into master for testing on dev.mvrt.com, that doesn't make sense. You have no response thusfar to my initial complaints.

**Comment by akalari** [comment]
1. Gulp serve testing
2. Push changes to develop for use on dev.mvrt.com
3. Test on various browsers
4. Merge changes into master for use on mvrt.com main website.

Hopefully this makes more sense?

**Comment by m3rcuriel** [comment]
No, because it addresses, once again, neither of the original questions.

**Comment by akalari** [comment]
I think I am a little confused on what the original question mean ><

**Comment by m3rcuriel** [comment]
1) Follow commit guidelines as can be found on confluence
2) if you're just gonna merge your own PRs, just push to master ><

**Comment by shovikguha** [comment]
@akalari 
Have you read the commit guidelines, because if you haven't I could see why you might be confused. It really doesn't make sense to merge your own pull requests into master so you can test on the dev site.

**Comment by m3rcuriel** [comment]
Adding on to what @shovikguha said, dev.mvrt.com is completely unrelated to master...

And again, the commit guidelines are on confluence.

**Pull request merged**
