### PR TITLE
incorporate some changes proposed by ryan

### PR DESCRIPTION
**Pull request by trotod**
* added/corrected some alumni colleges
* prefixed every mentor with a Mr./Mrs. (should we leave like this or not?)
* corrected/improved robot blurb for El Toro 17

Todo list [here](http://a.pomf.se/esezow.png)

still have to fix up gallery (which will likely come later), and make is clear that the blog is a private blog (which may involve revamping the members section, will also probably be something to do later)

### CODE REVIEW

**Comment by m3rcuriel** [comment]
Porque no es a develop?

**Comment by m3rcuriel** [comment]
@shovikguha any suggestions for blog rename?

**Comment by trotod** [comment]
I could close this and rebase onto master if you want me to.

**Comment by m3rcuriel** [comment]
Um... I meant rebase onto develop. plz

**Comment by trotod** [comment]
#61

**Pull request closed without merging**
